import os
import uuid
import json
import logging
from datetime import datetime
from typing import Any, Dict, Tuple, Optional

from openai import OpenAI
from cassandra.cluster import Cluster
from ai_core.db.client import ScyllaDBClient
from ..db.schema_init import ensure_schema
from typing_extensions import override

from .base_session_service import (
    BaseSessionService,
    GetSessionConfig,
    ListSessionsResponse,
    ListEventsResponse,
)
from .session import Session
from ..events.event import Event
from dotenv import load_dotenv, find_dotenv

print(f"[ScyllaSessionService Module Level] BEFORE load_dotenv, OPENAI_API_KEY: {os.getenv('OPENAI_API_KEY')}")
env_file_path = find_dotenv(usecwd=True)
print(f"[ScyllaSessionService Module Level] find_dotenv(usecwd=True) found: {env_file_path}")
if not env_file_path:
    env_file_path = find_dotenv()
    print(f"[ScyllaSessionService Module Level] find_dotenv() (default search) found: {env_file_path}")

loaded_dotenv_successfully = load_dotenv(dotenv_path=env_file_path if env_file_path else None, override=False)
print(f"[ScyllaSessionService Module Level] load_dotenv(path='{env_file_path}', override=False) returned: {loaded_dotenv_successfully}")
print(f"[ScyllaSessionService Module Level] AFTER load_dotenv, OPENAI_API_KEY: {os.getenv('OPENAI_API_KEY')}")

logger = logging.getLogger(__name__)

class ScyllaSessionService(BaseSessionService):
    """ScyllaDB-backed implementation of the session service."""

    def __init__(self):
        # Ensure the shared schema is initialized
        ensure_schema()
        self.client = ScyllaDBClient()
        self.ks = self.client._keyspace
        # Initialize OpenAI client for title/description generation
        print(f"[ScyllaSessionService __init__] Initializing OpenAI with key: {os.getenv('OPENAI_API_KEY')}")
        self.openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    def _generate_title_description(self, query: str, parameters: Dict[str, Any]) -> Tuple[str, str]:
        """Generate title and description using OpenAI GPT-4o mini based on query and parameters."""
        try:
            # Format parameters for context
            params_str = ", ".join([f"{k}: {v}" for k, v in parameters.items()]) if parameters else "None"
            
            # Create prompt for OpenAI
            prompt = f"""Based on the following query and parameters, generate a concise title and a brief description.
            
            If the query or parameters contain a GitHub URL (e.g., https://github.com/user/repo-name), please use the repository name (e.g., "repo-name") as the title.
            Otherwise, generate a concise title based on the query.
            
            Query: {query}
            Parameters: {params_str}
            
            Return only a JSON object with the following format:
            {{
                "title": "A concise title (max 30 chars, ideally the GitHub repo name if a URL is provided)",
                "description": "A brief description (max 50 chars)"
            }}
            """
            
            # Call OpenAI API
            response = self.openai_client.chat.completions.create(
                model="gpt-4o-mini",  # Use mini model for cost/speed
                messages=[
                    {"role": "system", "content": "You generate concise titles and descriptions for AI tasks."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=150,
                response_format={"type": "json_object"}
            )
            
            # Parse response
            content = response.choices[0].message.content.strip()
            result = json.loads(content)
            
            return result.get("title", "AI Task"), result.get("description", "Task generated by AI")
            
        except Exception as e:
            logger.error(f"Error generating title/description with OpenAI: {e}")
            # Fallback values
            return "AI Task", f"Task from query: {query[:30]}..."

    def create_session(
        self,
        *,
        app_name: str,
        user_id: str,
        state: dict[str, Any] | None = None,
        parameters: dict[str, Any] | None = None,
        session_id: str | None = None,
        query: Optional[str] = None,
        channel: Optional[str] = None, # depicsts voice, chat, email etc.
    ) -> Session:
        session_id = session_id or str(uuid.uuid4())
        now = datetime.utcnow()
        # Store app and user state if provided
        if state is None:
            state = {}
        if parameters is None:
            parameters = {}
        state_json = json.dumps(state)
        params_json = json.dumps(parameters)
        
        # Extract query from parameters if not provided directly
        if query is None and parameters and "query" in parameters:
            query = parameters.get("query")
            
        # Generate title and description based on query and parameters
        if query:
            title, description = self._generate_title_description(query, parameters)
            print(f"Generated title: {title}, description: {description}")  
        else:
            # Default values if no query available
            title = "AI Session"
            description = f"Session created for {app_name}"
            
        cql = (
            f"INSERT INTO {self.ks}.sessions "
            "(app_name, user_id, session_id, created_at, description, parameter, search_idx, state, status, title, updated_at, channel) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
        )
        
        status = "PENDING"

        # Build search_idx – concatenation of title and description, lower-cased and trimmed
        search_src = f"{title or ''}{description or ''}"
        search_idx = search_src.lower().strip() if search_src else None

        params = (
            app_name,
            user_id,
            session_id,
            now,
            description,
            params_json,
            search_idx,
            state_json,
            status,
            title,
            now,
            channel,
        )
        self.client.execute(cql, params)
        
        # Log the generated title and description
        logger.info(f"Created session with AI-generated title: '{title}', description: '{description}'")
        
        # Return the Session model
        return Session(
            id=session_id,
            app_name=app_name,
            user_id=user_id,
            state=state,
            parameters=parameters,
            events=[],
            last_update_time=now.timestamp(),
            channel=channel,
        )

    def update_session_status(
        self,
        *,
        app_name: str,
        user_id: str,
        session_id: str,
        status: str,
    ) -> None:
        """Update the status of a session in the database.
        
        Args:
            app_name: The name of the app.
            user_id: The ID of the user.
            session_id: The ID of the session.
            status: The new status to set (PENDING, RUNNING, COMPLETED, ERROR).
        """
        now = datetime.utcnow()
        cql = (
            f"UPDATE {self.ks}.sessions "
            "SET status = ?, updated_at = ? "
            "WHERE app_name = ? AND user_id = ? AND session_id = ?"
        )
        # app_name is team_id. user_id is org_id, session_id is session_id
        params = (status, now, app_name, user_id, session_id)
        self.client.execute(cql, params)
        logger.info(f"Updated session {session_id} status to {status}")

    def get_session_status(
        self,
        *,
        app_name: str,
        user_id: str,
        session_id: str,
    ) -> str:
        """Get the current status of a session from the database.
        
        Args:
            app_name: The name of the app.
            user_id: The ID of the user.
            session_id: The ID of the session.
            
        Returns:
            The current status of the session (PENDING, RUNNING, COMPLETED, ERROR, etc.).
            Returns "UNKNOWN" if the session is not found.
        """
        cql = (
            f"SELECT status FROM {self.ks}.sessions "
            "WHERE app_name = ? AND user_id = ? AND session_id = ? ALLOW FILTERING"
        )
        row = self.client.execute(cql, (app_name, user_id, session_id)).one()
        if not row:
            return "UNKNOWN"
        return row.status or "UNKNOWN"

    def get_session(
        self,
        *,
        app_name: str,
        user_id: str,
        session_id: str,
        config: GetSessionConfig | None = None,
        query: Optional[str] = None,  # Optional parameter, not used but included for API compatibility
    ) -> Session | None:
        # Fetch session row
        cql = (
            f"SELECT state, parameter, updated_at, status FROM {self.ks}.sessions "
            "WHERE app_name=? AND user_id=? AND session_id=?"
        )
        row = self.client.execute(cql, (app_name, user_id, session_id)).one()
        if not row:
            return None
        state = json.loads(row.state) if row.state else {}
        parameters = json.loads(row.parameter) if getattr(row, 'parameter', None) else {}
        last_update = row.updated_at.timestamp() if getattr(row, 'updated_at', None) else 0.0
        status = row.status if hasattr(row, 'status') and row.status else "PENDING"
        
        # Fetch events
        events_cql = f"SELECT * FROM {self.ks}.events " \
                     "WHERE app_name=? AND user_id=? AND session_id=?"
        rows = self.client.execute(
            events_cql, (app_name, user_id, session_id)
        )
        events = []
        for r in rows:
            loaded_content = json.loads(r.content) if r.content else None
            if loaded_content and isinstance(loaded_content.get("parts"), list):
                for part_data in loaded_content["parts"]:
                    if isinstance(part_data, dict):
                        # Safely remove 'thought_signature' if it exists from old data
                        part_data.pop("thought_signature", None)
                        # Also remove other potentially problematic fields found during previous fixes
                        if isinstance(part_data.get("function_response"), dict):
                            part_data["function_response"].pop("will_continue", None)
                            part_data["function_response"].pop("scheduling", None)
            
            ev = Event(
                id=r.event_id,
                author=r.author,
                branch=r.branch,
                invocation_id=r.invocation_id,
                content=loaded_content,  # Use the potentially modified content
                actions=json.loads(r.actions) if r.actions else {},
                timestamp=r.timestamp.timestamp(),
                long_running_tool_ids=set(),
                grounding_metadata=json.loads(r.grounding_metadata)
                    if r.grounding_metadata else {},
                partial=r.partial,
                turn_complete=r.turn_complete,
                error_code=r.error_code,
                error_message=r.error_message,
                interrupted=r.interrupted,
            )
            events.append(ev)
        return Session(
            id=session_id,
            app_name=app_name,
            user_id=user_id,
            state=state,
            parameters=parameters,
            events=events,
            last_update_time=last_update,
            status=status,
        )

    def list_sessions(
        self, *, app_name: str, user_id: str
    ) -> ListSessionsResponse:
        cql = f"SELECT session_id, updated_time, status FROM {self.ks}.sessions " \
              "WHERE app_name=? AND user_id=?"
        rows = self.client.execute(cql, (app_name, user_id))
        sessions = []
        for r in rows:
            status = r.status if hasattr(r, 'status') and r.status else "PENDING"
            sessions.append(
                Session(
                    id=r.session_id,
                    app_name=app_name,
                    user_id=user_id,
                    state={},
                    parameters={},
                    events=[],
                    last_update_time=r.updated_time.timestamp() if getattr(r, 'updated_at', None) else 0.0,
                    status=status,
                )
            )
        return ListSessionsResponse(sessions=sessions)

    def delete_session(
        self, *, app_name: str, user_id: str, session_id: str
    ) -> None:
        # Delete events first (to avoid FK issues)
        self.client.execute(
            f"DELETE FROM {self.ks}.events "
            "WHERE app_name=? AND user_id=? AND session_id=?",
            (app_name, user_id, session_id),
        )
        # Delete session row
        self.client.execute(
            f"DELETE FROM {self.ks}.sessions "
            "WHERE app_name=? AND user_id=? AND session_id=?",
            (app_name, user_id, session_id),
        )

    def list_events(
        self, *, app_name: str, user_id: str, session_id: str
    ) -> ListEventsResponse:
        cql = f"SELECT * FROM {self.ks}.events " \
              "WHERE app_name=? AND user_id=? AND session_id=?"
        rows = self.client.execute(cql, (app_name, user_id, session_id))
        events = []
        for r in rows:
            events.append(
                Event(
                    id=r.event_id,
                    author=r.author,
                    branch=r.branch,
                    invocation_id=r.invocation_id,
                    content=json.loads(r.content) if r.content else None,
                    actions=json.loads(r.actions) if r.actions else {},
                    timestamp=r.timestamp.timestamp(),
                    long_running_tool_ids=set(),
                    grounding_metadata=json.loads(r.grounding_metadata)
                        if r.grounding_metadata else {},
                    partial=r.partial,
                    turn_complete=r.turn_complete,
                    error_code=r.error_code,
                    error_message=r.error_message,
                    interrupted=r.interrupted,
                )
            )
        return ListEventsResponse(events=events)

    def append_event(self, session: Session, event: Event) -> Event:
        # Persist the event first
        now = datetime.utcnow()
        # Serialize event.content to JSON, swallowing errors
        if event.content:
            try:
                # Exclude 'thought_signature' from all parts when dumping to prevent validation errors on read
                # The structure {'parts': {'__all__': {'thought_signature': True}}} means:
                # for the 'parts' field, for all items in that list ('__all__'), exclude the 'thought_signature' field.
                content_dict = event.content.model_dump(exclude={'parts': {'__all__': {'thought_signature': True}}})
                content = json.dumps(content_dict)
            except Exception as e_dump:
                logger.warning(f"Failed to serialize event.content with specific exclude for 'thought_signature': {e_dump}. Trying broader fallback.")
                try:
                    # Fallback to simple model_dump if specific exclude failed for some reason (e.g., unexpected structure)
                    content = json.dumps(event.content.model_dump())
                except Exception as e_dump_fallback:
                    logger.warning(f"Failed to serialize event.content with model_dump: {e_dump_fallback}. Trying str().")
                    try:
                        content = json.dumps(str(event.content))
                    except Exception as e_str_dump:
                        logger.error(f"Failed to serialize event.content even with str(): {e_str_dump}")
                        content = None
        else:
            content = None
        # Serialize event.actions to JSON (use model_dump), swallowing errors
        if event.actions:
            try:
                actions = json.dumps(event.actions.model_dump())
            except Exception:
                try:
                    actions = json.dumps(str(event.actions))
                except Exception:
                    actions = None
        else:
            actions = None
        # Serialize grounding_metadata to JSON, swallowing errors
        if event.grounding_metadata:
            try:
                grounding = json.dumps(event.grounding_metadata.model_dump())
            except Exception:
                try:
                    grounding = json.dumps(str(event.grounding_metadata))
                except Exception:
                    grounding = None
        else:
            grounding = None
        cql = f"INSERT INTO {self.ks}.events " \
              "(app_name, user_id, session_id, event_id, invocation_id, " \
              "author, agent_id, branch, timestamp, content, actions, grounding_metadata, " \
              "partial, turn_complete, error_code, error_message, interrupted) " \
              "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
        params = (
            session.app_name,
            session.user_id,
            session.id,
            event.id,
            event.invocation_id,
            event.author,
            event.agent_id,
            event.branch,
            now,
            content,
            actions,
            grounding,
            event.partial,
            event.turn_complete,
            event.error_code,
            event.error_message,
            event.interrupted,
        )
        self.client.execute(cql, params)
        
        # Update session's last_update_time
        session.last_update_time = now.timestamp()
        
        # Update session status based on event properties
        if event.error_code or event.error_message:
            # If there's an error, update status to ERROR
            self.update_session_status(
                app_name=session.app_name, 
                user_id=session.user_id, 
                session_id=session.id, 
                status="FAILURE"
            )
        elif event.turn_complete:
            # If the turn is complete (final event), update status to COMPLETED
            self.update_session_status(
                app_name=session.app_name, 
                user_id=session.user_id, 
                session_id=session.id, 
                status="SUCCESS"
            )
            
        return super().append_event(session, event)

    @override
    def update_session_parameters(
        self,
        *,
        app_name: str,
        user_id: str,
        session_id: str,
        parameters: dict[str, Any],
    ) -> Optional[Session]:
        """Updates the parameters of an existing session in ScyllaDB."""
        now = datetime.utcnow()
        params_json = json.dumps(parameters or {})

        # First, check if the session exists to avoid updating a non-existent one
        # (though UPDATE is idempotent, get_session later would fail)
        existing_session_check = self.client.execute(
            f"SELECT session_id FROM {self.ks}.sessions WHERE app_name=? AND user_id=? AND session_id=?",
            (app_name, user_id, session_id)
        ).one()

        if not existing_session_check:
            logger.warning(f"Session not found, cannot update parameters: {app_name}/{user_id}/{session_id}")
            return None

        cql = (
            f"UPDATE {self.ks}.sessions "
            "SET parameter = ?, updated_at = ? "
            "WHERE app_name = ? AND user_id = ? AND session_id = ?"
        )
        update_params_tuple = (params_json, now, app_name, user_id, session_id)
        self.client.execute(cql, update_params_tuple)
        logger.info(f"Updated parameters for session {session_id}")

        # Return the updated session by calling get_session to ensure consistency
        return self.get_session(app_name=app_name, user_id=user_id, session_id=session_id) 